name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 20
    - name: install
      run: npm ci && npm install react preact vue
    - name: build
      run: npm run build
      env:
        CI: true
    - name: test
      run: npm run test
      env:
        CI: true
    - name: e2e
      run: npm run e2e
      env:
        CI: true
    - name: lint
      run: npm run lint
      env:
        CI: true
